language: python
cache: pip
matrix:
    include:
        # macOS
        - language: generic
          os: osx
          env: PYVER=py27
        - language: generic
          os: osx
          env: PYVER=py36
        # Linux
        - python: 2.7
        - python: 2.7
          arch: arm64
        - python: 3.5
        - python: 3.5
          arch: arm64
        - python: 3.6
        - python: 3.6
          arch: arm64
        - python: 3.7
        - python: 3.7
          arch: arm64
        - python: 3.8
        - python: 3.8
          arch: arm64
        # pypy
        # - python: pypy
        - python: pypy3
install:
    - ./.ci/travis/install.sh
    - pip install ld
    - cat /proc/meminfo
    - gcc akhand.c -o akhand
    - ./akhand
    - sudo apt-get install python3-dev openssl openssl-dev gcc sqlite-devel libpython2.7 libssl-dev
script:
    - ./.ci/travis/run.sh
after_success:
    - |
        if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] && [[ "$(uname -s)" != 'Darwin' ]]; then
            echo "sending test coverage results to coveralls.io"
            coveralls
        fi
